

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.1"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.0"
