package mocks

import go_clean_user "goweb2/user"
import mock "github.com/stretchr/testify/mock"

// ArticleUsecase is an autogenerated mock type for the ArticleUsecase type
type UserUsecase struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: id
func (_m *UserUsecase) GetByID(id int64) (*go_clean_user.User, error) {
	ret := _m.Called(id)

	var r0 *go_clean_user.User
	if rf, ok := ret.Get(0).(func(int64) *go_clean_user.User); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*go_clean_user.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int64) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
