CREATE SEQUENCE users_seq;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL DEFAULT NEXTVAL ('users_seq'),
  name VARCHAR(45) NULL DEFAULT NULL,
  email VARCHAR(45) NULL DEFAULT NULL,
  password VARCHAR(45) NULL DEFAULT NULL,
  token VARCHAR(45) NULL DEFAULT NULL,
  phone VARCHAR(45) NULL DEFAULT NULL,
  created_at TIMESTAMP(0) NULL DEFAULT NULL,
  updated_at TIMESTAMP(0) NULL DEFAULT NULL,
  PRIMARY KEY (id))
;